name: Build Forgejo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      packages: write
    steps:

      - name: Clone forgejo
        run: git clone --depth=1 --single-branch https://codeberg.org/forgejo/forgejo.git .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push forgejo
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          push: true
          #cache-from: type=registry,ref=boxinaclosedbox/forgejo:buildcache
          #cache-to: type=registry,ref=boxinaclosedbox/forgejo:buildcache,mode=max
          tags: |
                 ghcr.io/boxinaclosedbox/forgejo:latest
                 boxinaclosedbox/forgejo:latest
          file: Dockerfile

      - name: Build and push forgejo rootless
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          push: true
          #cache-from: type=registry,ref=boxinaclosedbox/forgejo:buildcache
          #cache-to: type=registry,ref=boxinaclosedbox/forgejo:buildcache,mode=max
          tags: |
                 ghcr.io/boxinaclosedbox/forgejo:latest-rootless
                 boxinaclosedbox/forgejo:latest-rootless
          file: Dockerfile.rootless